#include <iostream>
#include <stdexcept>
using namespace std;

class Test {
public:
    static int tableau[];
public:
    static int division(int indice, int diviseur) {
        if (indice < 0 || indice >= 10) {
            throw out_of_range("Indice en dehors de la plage du tableau.");
        }
        if (diviseur == 0) {
            throw invalid_argument("Division par zéro.");
        }
        return tableau[indice] / diviseur;
    }
};

int Test::tableau[] = {17, 12, 15, 38, 29, 157, 89, -22, 0, 5};

int main() {
    int x, y;
    cout << "Entrez l'indice de l'entier à diviser : " << endl;
    cin >> x;

    try {
        cout << "Entrez le diviseur : " << endl;
        cin >> y;
        int resultat = Test::division(x, y);
        cout << "Le résultat de la division est : " << resultat << endl;
    } catch (const out_of_range& e) {
        cerr << "Erreur : " << e.what() << endl;
    } catch (const invalid_argument& e) {
        cerr << "Erreur : " << e.what() << endl;
    }

    return 0;
}
